name: Reusable Test Workflow
on:
  workflow_call:
    inputs:
      deps-directory:
        description: What folder to search for requirements.
        required: true
        type: string
      source-directory:
        description: What folder to search for requirements.
        required: true
        type: string
      module-directory:
        description: What folder to analyze.
        required: true
        type: string

    outputs:
      coverage_report_path:
        description: "Pytest Coverage Report Path"
        value: ${{ jobs.Test.outputs.coverage }}
      execution_report_path:
        description: "Pytest Execution Report Path"
        value: ${{ jobs.Test.outputs.execution }}

jobs:
  Test:
    runs-on: ubuntu-latest
    outputs:
      coverage: pytest-cov-results/coverage.xml
      execution: pytest-exec-results/xunit-result.xml
    steps:
      - name: Load Cache & Dependencies
        uses: TeiaLabs/python-dependencies-action@master
        with:
          deps-directory: ${{ inputs.deps-directory }}
          application: true
          test: true

      - name: Test Module
        run: pytest ${{ inputs.module-directory }} --cov=${{ inputs.module-directory }} --cov-report xml --junitxml=xunit-result.xml
        working-directory: ${{ inputs.source-directory }}

      - name: Upload pytest execution results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-exec-results
          path: ${{ inputs.source-directory }}/xunit-result.xml

      - name: Upload pytest coverage results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-cov-results
          path: ${{ inputs.source-directory }}/coverage.xml
